name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install OpenTelemetry C++
        run: |
          brew update
          brew install opentelemetry-cpp

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  merge_wheels:
    name: Merge wheel artifacts
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-wheels
          pattern: wheels-*
          merge-multiple: true

      - name: Upload merged wheels
        uses: actions/upload-artifact@v4
        with:
          name: all-wheels
          path: all-wheels/*.whl
          if-no-files-found: error

      - name: List wheels
        run: ls -lh all-wheels/
